[book]
authors = ["Lut99"]
language = "en"
multilingual = false
src = "src"
title = "Main page"

[output.html]
default-theme = "navy"
site-url = "/"
git-repository-url = "https://github.com/epi-project/brane"
git-repository-icon = "fa-github"
